
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana Slovensko | Šablona stránek
email: to@pirati.sk
description: > # this means to ignore newlines until "baseurl:"
  Zde doplně popis webu
url: "https://pirati.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Styleguide base URL, see the list of available options here: https://styleguide.pir-test.eu/
# styleguide_base_url: https://styleguide.pir-test.eu/1.x.x

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-environment-variables

paginate_path: "/aktuality/:num/"
paginate: 12

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-pirati-sk.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - vendor
  - assets/js
  - config

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

js_base_url: '/assets/js/'

# Make sure webpack-generated assets are not purged by Jekyll
keep_files:
  - assets/js

permalink: /aktuality/:title.html

collections:
  people:
    output: true
    permalink: /ludia/:path/

  program:
    output: true
    permalink: /komunalne-volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
         - profile
         - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

emptyArray: []

organization:
  name: Pirátská strana # Jmeno skupiny používající web - př Pirátská strana
  shortName: Název skupiny # Kratší název skupiny
  email: example@pirati.cz
  phone: +420 777 123 456 789
  address: |
    Piratská planeta 1
    100 00 Pirátsko
  residenceImg: people/ppp.jpg
  mapLink: https://mapy.cz/zakladni?base=ophoto&q=Radou%C5%A1ova%2014,%20Chrudim
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  donateLink: https://dary.pirati.sk/
  onboardingLink: https://nalodeni.pirati.sk

# Items listed in contact summary table
contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite
  - type: custom
    iconClass: ico--pirati
    label: Vlastní řádek tabulky
    body: <a href="http://example.com">link</a>

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Celoštátny kalendár 
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=nk73m1m89vhf5g2vojp6tnqe58%40group.calendar.google.com&ctz=Europe%2FPrague&amp;color=%232952A3

facebook:
  loadSDK: true
  profilePage: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiMhILky4H1AhUyi_0HHSABCoIQFnoECAIQAQ&url=https%3A%2F%2Fwww.facebook.com%2Fpiratskastrana&usg=AOvVaw2Ouy6YukNvDLBb8jZjw_LO
  profilePageName: Facebook profil
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: SlovenskiPirati


instagram:
  profilePage: https://www.instagram.com/slovenskipirati/

github:
  url: https://github.com/mkrejpsky/jekyll-theme-pirati-sk/
  branch: master


assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - node_modules
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
